### ISSUE TITLE
[BUG]: Missing or malformed appsetting "DiscordBotAdminUser" causes program to exit without warning

### ISSUE THREAD

**Issue by Krypton-Nova** [drehtisch/CyborgianStates#50]
**Describe the bug**
When "DiscordBotAdminUser" in appsettings(.development).json is not filled or malformed (by entering a Discord username, for example), the application exits without logging any information and with exit code 0.

**To Reproduce**
1. Use the settings found in the default appsettings.json
2. Run Program.cs

**Expected behavior**
Program logs the issue and exits.

**On which MessageHandler occured the error (e.g. Console, Discord)?:**
Console.

**Additional context**
When debugging this on Linux, I received a SIGSEGV (segmentation fault) and [heap dump](https://github.com/drehtisch/CyborgianStates/files/4638691/paste.txt).

**Screenshots**
System information:
![system](https://user-images.githubusercontent.com/38065396/82124680-f4739b00-97a0-11ea-9590-9e4d1ced0dc4.png)

**Comment by Krypton-Nova** [comment]
If the issue cannot be found or solved trough code, writing documentation for the settings (which are required, what is expected, and so on) would solve it too.

**Comment by drehtisch** [comment]
I was able to reproduce this. I'm looking at the issue.
